FROM python:3.11-slim AS builder

WORKDIR /install

COPY requirements.txt .

RUN pip install --prefix=/install --no-cache-dir -r requirements.txt


FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY --from=builder /install /usr/local

COPY app ./app

CMD ["python", "-m", "app.kafka.consumer"]